src/main/java/me/willdawson/subview/controller/BaseController.java
package me.willdawson.subview.controller;

import me.willdawson.subview.dao.UserDAO;
import me.willdawson.subview.model.User;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

/**
 * BaseController should be used to extend all controllers. It provides a number of
 * helpful methods.
 */

@Named
@RequestScoped
public class BaseController {

    private User auth;

    public BaseController() {
        auth = getAuthUser();
    }

    protected HttpServletRequest getRequest() {
        FacesContext context = FacesContext.getCurrentInstance();
        return (HttpServletRequest) context.getExternalContext().getRequest();
    }

    /**
     * A nicer way to handle faces redirect URLs.
     *
     * @param url
     * @return
     */
    protected String redirect(String url) {
        url = (url.indexOf("?") == -1) ? url + "?" : url + "&";
        return url + "faces-redirect=true";
    }

    /**
     * Shows a FacesMessage with no severity level.
     *
     * @param message
     */
    protected void showSuccess(String message) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(message));
    }

    /**
     * Shows a FacesMessage with a level of SEVERITY_ERROR.
     *
     * @param message
     */
    protected void showError(String message) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }

    /**
     * Get the authenticated user object.
     *
     * @return The authenticated user.
     */
    public User getAuthUser() {
        if (auth == null) {
            String username = FacesContext.getCurrentInstance().getExternalContext().getRemoteUser();
            auth = new UserDAO().findByUtsId(username);
        }

        return auth;
    }

}

src/main/web/WEB-INF/partials/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:c="http://java.sun.com/jsp/jstl/core">

    <header class="site-header">
        <a href="/" class="logo">Subview</a>

        <div class="site-header__auth">
            <ul>
                <ui:fragment rendered="#{not empty baseController.authUser}">
                    <li><a href="/account.xhtml">#{baseController.authUser.name}</a></li>
                    <li><h:form><h:commandLink value="Logout" action="#{authController.logout}" /></h:form></li>
                </ui:fragment>

                <ui:fragment rendered="#{empty baseController.authUser}">
                    <li><a href="/login.xhtml">Login</a></li>
                    <li><a href="/signup.xhtml">Signup</a></li>
                </ui:fragment>
            </ul>
        </div>
    </header>

</ui:composition>

src/main/web/WEB-INF/partials/navigation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:c="http://java.sun.com/jsp/jstl/core">

    <nav class="site-navigation">
        <ul>
            <ui:fragment rendered="#{not empty baseController.authUser}">
                <li><h:link value="Write a Review" outcome="/review/create" /></li>
            </ui:fragment>
            <li><h:form><h:commandLink value="Export Reviews" action="#{csvController.export}" /></h:form></li>
        </ul>

        <span class="site-navigation__heading">Subjects</span>
        <ul>
            <ui:repeat var="subject" value="#{indexController.subjects}">
                <li><h:link value="#{subject.utsId} #{subject.abbreviation}" outcome="/subject/index?id=#{subject.id}" /></li>
            </ui:repeat>
        </ul>
    </nav>

</ui:composition>